In [98]:
import pandas as pd
import numpy as np
import nltk

In [99]:
df = pd.DataFrame.from_csv('/Users/kaitlin/ds/metis/metisgh/Puryear_Metis/Project4/shortjokes.csv', 
                      header=0, 
                      sep=',', 
                      index_col=0, 
                      parse_dates=True, 
                      encoding=None, 
                      tupleize_cols=None, 
                      infer_datetime_format=False)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:8: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls

In [100]:
df.head(20)

                                                 Joke
ID
1   [me narrating a documentary about narrators] "...
2   Telling my daughter garlic is good for you. Go...
3   I've been going through a really rough period ...
4   If I could have dinner with anyone, dead or al...
5      Two guys walk into a bar. The third guy ducks.
6   Why can't Barbie get pregnant? Because Ken com...
7    Why was the musician arrested? He got in treble.
8   Did you hear about the guy who blew his entire...
9   What do you do if a bird shits on your car? Do...
10  He was a real gentlemen and always opened the ...
11  Telling my daugthers date that "she has lice a...
12  What should you do before criticizing Pac-Man?...
13  What's the difference between an illegal Mexic...
14  What do you call a barbarian you can't see? an...
15             How do you spell Canda? C,eh,N,eh,D,eh
16  You ever notice that the most dangerous thing ...
17  What did Arnold Schwarzenegger say at the abor...
18  My wife is in a bad mood. I think her boyfrien...
19  My speech today will be like a mini-skirt. Lon...
20  Thanksgiving joke What does Miley Cyrus eat fo...

In [128]:
from nltk.tokenize import sent_tokenize

text = df["Joke"][90]

sentences = sent_tokenize(text)
print(sentences)

['What do you call a three-humped camel?', 'Pregnant (Told to me by one of the kids at work)']

In [116]:
first = df["Joke"][1]

In [117]:
trial = TextBlob(first)
trial.ngrams(1)

[WordList(['me']),
 WordList(['narrating']),
 WordList(['a']),
 WordList(['documentary']),
 WordList(['about']),
 WordList(['narrators']),
 WordList(['I']),
 WordList(['ca']),
 WordList(["n't"]),
 WordList(['hear']),
 WordList(['what']),
 WordList(['they']),
 WordList(["'re"]),
 WordList(['saying']),
 WordList(['cuz']),
 WordList(['I']),
 WordList(["'m"]),
 WordList(['talking'])]

In [118]:
trial.sentiment

Sentiment(polarity=0.0, subjectivity=0.0)

In [108]:
listo = [["polarity", "subjectivity"]]
for i in range(len(df)):
    test = (TextBlob(df["Joke"][i+1])).sentiment
    listo.append(test)
a = np.array(listo)

In [109]:
a

array([['polarity', 'subjectivity'],
       ['0.0', '0.0'],
       ['0.7', '0.6000000000000001'],
       ...,
       ['0.0', '0.0'],
       ['0.0', '0.0'],
       ['0.08', '0.52']],
      dtype='<U23')

In [110]:
dt = pd.DataFrame(data=a[1:,1:],    # values
             index=a[1:,0],    # 1st column as index
             columns=a[0,1:])  # 1st row as the column names

In [111]:
dt = dt.reset_index(drop=False)
dt = dt.rename(index=str, columns={'index': 'polarity'})

In [112]:
dt.head(40)

                 polarity         subjectivity
0                     0.0                  0.0
1                     0.7   0.6000000000000001
2                    0.25                  0.7
3                     0.0   0.4000000000000001
4                     0.0                  0.0
5     0.16666666666666666                 0.55
6                     0.0                  0.0
7                     0.0               0.3125
8                     0.0                  0.0
9                     0.2  0.30000000000000004
10                    0.2                  0.3
11                    0.0                  0.0
12  -0.024999999999999994                  0.3
13                   -0.7                 0.95
14                    0.0                  0.0
15   -0.04999999999999999                  0.7
16                    0.0  0.06666666666666667
17    -0.6999999999999998   0.6666666666666666
18                -0.0125                0.425
19                    0.0                  0.0
20                    0.7   0.6000000000000001
21                    0.0                  0.0
22   -0.04464285714285714  0.35714285714285715
23                    0.0                  0.0
24                    0.0                  0.0
25                    0.0                  0.0
26                    0.0                  0.0
27                -0.3625               0.6625
28                    0.0                  0.0
29                    0.0                  1.0
30                    0.5                  0.5
31                    0.5                  0.4
32                    0.0                  0.1
33                    0.0                  0.0
34   -0.15555555555555559   0.2888888888888889
35                   0.25                  1.0
36                    0.0                  0.0
37                    0.5                  1.0
38                    0.0                  0.0
39   -0.09047619047619049  0.27976190476190477